package bot.utils;

import java.util.List;

public enum City  {

    SOFIA("София",List.of("SOF","Safija","Serdica","Sofi","сф","IEC","inter expo","интер експо","sf","Sofia","Sofiae","Sofie","Sofii","Софий","София","Софија","Софія","студентски"),1152556,new double[]{42.69751,23.32415}),
    PLOVDIV("Пловдив",List.of("Plovdin","Plovdiv","Plowdiw","Пловдив"),340494,new double[]{42.15,24.75}),
    VARNA("Варна",List.of("Варна","varna","warna"),312770,new double[]{43.21667,27.91667}),
    BURGAS("Бургас",List.of("Boergas","Bourgas","Bournkas","Burgas","bs","бс","Burgaz","Burghaz","Бургас"),195966,new double[]{42.50606,27.46781}),
    RUSE("Русе",List.of("ROU","Roese","Rouse","Rousse","Ruse","Russe","Русе"),156238,new double[]{43.84872,25.9534}),
    STARA_ZAGORA("Стара Загора",List.of("SZR","Stara Sagora","Stara Zagora","ст. загора","ст.загора","stz","стз","Stara-Zagora","Stara-Zagorae","Стара Загора"),143431,new double[]{42.43278,25.64194}),
    PLEVEN("Плевен",List.of("Pleven","Plevna","Plevne","Plewen","Плевен","плн"),118675,new double[]{43.41667,24.61667}),
    SLIVEN("Сливен",List.of("Islimiye","Islimje","Sliven","Slivenas","Slivno","Сливен","Слівен"),96368,new double[]{42.68583,26.32917}),
    DOBRICH("Добрич",List.of("Bazargic","Dobric","Dobrich","Dobrici","Dobricius","Dobricz","Dobritch","Dobritj","Dobrits","Dobritsch","Dobritsj","Dobritx","Dobritš","Dobriç","Dobriĉ","Dobrič","Dobričius","Dobrych","Dòbritx","Hadzi-Oghlu-Pazardzik","Hadži-Oghlu-Pazardžik","Khadzhioglu Bazardzhik","Khadzhioglu Pazardzhik","Ntomprits","Tolbuhin","Tolbukhin","dobeulichi","doburichi","duo bu li qi","dwbrch","dwbrych","dwbrytsh","dwbryz","Ντόμπριτς","Добрич","Добрыч","Դոբրիչ","דובריץ","دوبريتش","دوبرچ","دوبریچ","ドブリチ","多布里奇","도브리치"),94831,new double[]{43.56667,27.83333}),
    SHUMEN("Шумен",List.of("Choumen","Choumèn","Kolarovgrad","Schumen","Shoumen","Shumen","Shumla","Sjumen","Sumen","Sumla","Sumnu","shumen","Şumnu","Šumen","Šumla","Шумен"),87283,new double[]{43.27064,26.92286}),
    PERNIK(List.of("Dimitrovo","Pernik","Pernikas","brnyk","pei er ni ke","peleunikeu","per nik","peruniku","prnyk","prnyq","pyrnk","Πέρνικ","Перник","Пернік","פרניק","برنيك","پرنیک","پیرنک","پێرنیک","เปร์นิก","ペルニク","佩尔尼克","페르니크"),82467,new double[]{42.6,23.03333}),
    YAMBOL(List.of("Iambol","JAM","Jambol","Jamboli","Yambol","Yampolis","Ямбол"),80116,new double[]{42.48333,26.5}),
    SINEMORETZ(List.of("Sinemorec","Sinemoretz","Синеморец","Синеморетс"),10000,new double[]{42.05837,27.98382}),
    BOROVETZ(List.of("Sinemorec","Sinemoretz","Синеморец","Синеморетс"),10000,new double[]{42.258,23.604164}),
    PAMPOROVO(List.of("Pamporovo","Pumpurovo","Пампорво","Пъмпорово"),10000,new double[]{41.649997,24.68333}),
    SHKORPILOVCI(List.of("Shkorpilovci","Шкорпиловци"),10000,new double[]{42.96666667,27.88305556}),
    HASKOVO(List.of("Chaskoi","Chaskovas","Chaskovo","Chaskowo","Chasköi","HKV","Haskioj","Haskiöj","Haskovo","Haskoy","Hasköy","Khaskava","Khaskovo","Khàskovo","ha si ke wo","haseukobo","haskwfw","hasukovu~o","khaskww","Ĥaskovo","Χάσκοβο","Хаскава","Хасково","חאסקובו","خاسکوو","خاسکۆڤۆ","هاسكوفو","هاسکوفو","ہسکوا","ハスコヴォ","哈斯科沃","하스코보"),79699,new double[]{41.93415,25.55557}),
    PAZARDZHIK(List.of("Pasardschik","Pasardshik","Pazarcik","Pazarcık","Pazardjik","Pazardsjik","Pazardzhik","Pazardzik","Pazardzikas","Pazardzjik","Pazardĵik","Pazardżik","Pazardžik","Pazardžikas","Pazartzik","Pàzardjik","Tatar Bazardzik","Tatar Bazardžik","Tatar Pazardjik","Tatar Pazardzhik","Tatar Pazardzik","Tatar Pazardžik","Tatar-Bazardzhik","bazarjyk","pa sar cik","pa zha er ji ke","pajaleujikeu","pazarjk","pazarjyk","pazarjyk  blgharstan","pazarjyk  bwlgarya","pazarujiku","Πάζαρτζικ","Пазарджик","Пазарџик","פאזארדזיק","بازارجيك","پازارجک","پازارجیک","پازارجیک، بلغارستان","پازارجیک، بولگاریا","ปาซาร์จีก","パザルジク","帕扎爾吉克","파자르지크"),75977,new double[]{42.2,24.33333}),
    BLAGOEVGRAD(List.of("Blagoeugrad","Blagoevgrad","Blagoewgrad","Blagojevgrad","Blagojevgradas","Blagojewgrad","Blagoëvgrad","Blagòevgrad","Blankoevnkrant","Blaqoyevqrad","Błagojewgrad","Djumaja","Dzhumaya","Dzuma","Dzumaja","Džuma","Džumaja","Gorna Djoumaia","Gorna Djumaya","Gorna Dshumaja","Gorna Dzhumaja","Gorna Dzhumaya","Gorna Dzumaja","Gorna Džumaja","Yukari Cuma","Yukarı Cuma","beullago-ebeugeuladeu","blaghwyfghrad","blagoevgradi","blagwwgrad","blagwyywgrad","bu la ge ye fu ge lei","buragoevugurato","Μπλαγκόεβγκραντ","Благоевград","Благоеўград","Благоєвград","Горна Джумая","Բլագոևգրադ","בלגואבגרד","بلاغويفغراد","بلاگوئیوگراد","بلاگووگراد","ბლაგოევგრადი","ブラゴエヴグラト","布拉戈耶夫格勒","블라고에브그라드"),71306,new double[]{42.01667,23.1}),
    VELIKO_TURNOVO(List.of("Tarnovo","Tarnowo","Ternovo","Tirnovo","Trnova","Trnovo","Turnovo","Tărnovo","Tărnowo","Tŭrnovo","Veliko Trnovo","Veliko Tarnovo","Veliko Tărnovo","Weliko Tarnowo","Wielkie Tyrnowo","в.търново","vu~eriko・tarunovu~o","Велико Търново","ヴェリコ・タルノヴォ"),66217,new double[]{43.08124,25.62904}),
    GABROVO(List.of("Gabrava","Gabrova","Gabrovas","Gabrovo","Gabrowo","Gàbrovo","Nkamprovo","gabeulobo","gabrww","gabrwww","gaburovu~o","gbrwbw","gbrwwa","ghabrwfw","jia bu luo wo","Γκάμπροβο","Габрава","Габрово","Գաբրովո","גברובו","غابروفو","گابروو","گابرووو","گابرۆڤۆ","گبرووا","ガブロヴォ","加布羅沃","가브로보"),66175,new double[]{42.87472,25.33417}),
    VRATSA(List.of("Ivraca","Vraca","Vracae","Vrata","Vratca","Vratsa","Vrattsa","Vratza","Vrața","Wraca","Wraza","beulacha","fratsa","fu la cha","vratsa","vuratsu~a","wratsa","İvraca","Βράτσα","Врацæ","Враца","וראצה","فراتسا","وراتسا","ڤراتسا","ヴラツァ","弗拉察","브라차"),64941,new double[]{43.21,23.5625}),
    KAZANLAK(List.of("Kasanlak","Kasanlăk","Kazanlk","Kazanlak","Kazanlako","Kazanlek","Kazanlik","Kazanlk","Kazanluk","Kazanlyk","Kazanlăk","Kazanlık","Kazanlŭk","Kazanłyk","qʼzʼnlq","Казанлък","Казанлык","קאזאנלק"),55196,new double[]{42.61667,25.4}),
    VIDIN(List.of("Vidin","Vidinas","Vidine","Vidinu","Vintin","Widin","Widyn","Widyń","bidin","fydn","vu~idin","wdyn","wei ding","wydyn","Βίντιν","Видин","Видинъ","וידין","فيدن","ودین","ویدین","ヴィディン","維丁","비딘"),54409,new double[]{43.99159,22.88236}),
    ASENOVGRAD(List.of("Asenovgrad","Assenovgrad","Assenovgrade","Assenowgrad","Stanimaka","Асеновград"),52170,new double[]{42.01667,24.86667}),
    KARDZHALI(List.of("Exrdzhali","Kardjali","Kardschali","Kardshali","Kardzali","Kardzhali","Kardzjali","Kardĵali","Kardžali","Kartzali","Kerdzalai","Kerdzhali","Kerdžalai","Kerjali","Kircaali","Kirdjalu","Kirdjalü","Kirdzali","Kirdzalu","Kirdzhali","Kirdžali","Kirdžalü","Kirjali","Krdjali","Krdzali","Krdžali","Kudjaly","Kurdzali","Kurdzhale","Kurdzhali","Kurdzhalii","Kyakyrdzhali","Kyrdzali","Kyrdzhali","Kyrdżali","Kărdjali","Kărdzhali","Kărdžali","Kırcaali","Kŭrdzhale","Kŭrdzhali","Kŭrdzhalii","Kŭrdžali","kardzhaly","karjly","ke er gu li","keoleujalli","kurujari","Κάρτζαλι","Кирджалі","Крџали","Кърджали","Кырджали","קרדזאלי","كارجلي","کاردژالی","კირჯალი","クルジャリ","克爾賈利","커르잘리"),51000,new double[]{41.65,25.36667}),
    KYUSTENDIL(List.of("Keustendil","Kioustendil","Kioustentil","Kiousténdil","Kjustendil","Koestendil","Kostendil","Kustendil","Kyustendil","Köstendil","Küstendil","Κιουστεντίλ","Кюстендил"),48286,new double[]{42.28389,22.69111}),
    MONTANA(List.of("Ferdinand","Ferdinandovo","Golyama Kutlovitsa","Khristo Mikhaylov","Kutlovica","Kutlu Vice","Kutlu Viçe","Mikhailovgrad","Mikhaylovgrad","Montana","Montanae","Velika Kutlovica","meng ta na","montana","mwntana","mwntana  blgharstan","mwntnh","Μοντάνα","Монтанæ","Монтана","Монтана · Блъгарїи","מונטנה","مونتانا","مونتانا، بلغارستان","مۆنتانا، بولگاریا","モンタナ","蒙塔納","몬타나"),47445,new double[]{43.4125,23.225}),
    DIMITROVGRAD(List.of("Dimitrovgrad","Dimitrovgradas","Dimitrowgrad","Ntimitrovnkrant","dimiteulobeugeuladeu","dymytrwfgrad  blgharstan","dymytrۆvgrad  bwlgarya","ji mi te luo fu ge lei","Ντιμίτροβγκραντ","Димитровград","Димитровъ Градъ · Блъгарїи","דימיטרובגראד","دیمیتروفگراد، بلغارستان","دیمیترۆڤگراد، بولگاریا","季米特洛夫格勒","디미트로브그라드"),43288,new double[]{42.05,25.6}),
    LOVECH(List.of("Lavech","Lofca","Lofça","Lovca","Lovcha","Lovec","Lovecas","Lovech","Loveci","Lovetch","Lovetj","Lovets","Lovetsj","Lovetš","Loveĉ","Loveč","Lovečas","Lovča","Lowecz","Lowetsch","Melta","lobechi","luo wei qi","lwbz","lwftsh","lwwch","lwwych","rovu~echi","Łowecz","Λόβετς","Лавеч","Ловеч","לובץ","لوفتش","لووچ","لوویچ","لۆڤێچ","ロヴェチ","洛維奇","로베치"),42211,new double[]{43.13333,24.71667}),
    SILISTRA(List.of("Dristra","Durostorum","SLS","Silistra","Silistrae","Silistre","Szilisztra","shirisutora","si li s tra","silliseuteula","sylstra","sylystra","sylystrh","xi li si te la","Σιλίστρα","Силистрæ","Силистра","Сілістра","סיליסטרה","سيليسترا","سیلسترا","سیلیسترا","ซิลิสตรา","シリストラ","錫利斯特拉","실리스트라"),39715,new double[]{44.1171,27.26056}),
    RAZGRAD(List.of("Rasgrad","Razgrad","Razgradas","Raznkrant","Ràzgrad","la zi ge lei","lajeugeuladeu","razghrad","razgrad","razugurato","Ράζγκραντ","Разград","ראזגרד","رازغراد","رازگراد","رازگراڈ","ラズグラト","拉茲格勒","라즈그라드"),38285,new double[]{43.53333,26.51667}),
    TARGOVISHTE(List.of("Eski Cuma","Eski Djoumaia","Eski Djoumaïa","Eski Dschumaja","Eski Dzhumaya","Eski Dzuma","Eski Dzumaja","Eski Dzumaya","Eski Džuma","Eski Džumaja","TGV","Targovichte","Targovichté","Targovishte","Targovisjte","Targoviste","Targovixte","Targoviŝte","Targowischte","Targòvixte","Tarnkoviste","Tergovishce","Tergoviste","Tergovištė","Tirgovishte","Trgovishte","Trgoviste","Trgovište","Turgovishhe","Turgovishte","Turgoviste","Tyrgovishte","Tyrgowiszte","Tërgovishçe","Tărgovište","Tărgoviște","Tărgowischte","Tŭrgovishte","Tŭrgovište","Tǎrgovište","targhwfyshth","te er ge wei shen te","teoleugobisyute","trgwbysth","Ταργκόβιστε","Тирговиште","Трговиште","Търговище","Тырговиште","טרגובישטה","تارغوفيشته","ترگوویشتے","ترگوویشتے ،بلغاریہ","特爾戈維什特","터르고비슈테"),37774,new double[]{43.2512,26.57215}),
    DUPNITSA(List.of("Doepnitsa","Doupnitsa","Doupnitza","Dubnica","Dupnica","Dupnicja","Dupnita","Dupnitsa","Dupnitza","Dupniza","Dupnița","Marek","Ntoupnitsa","Stanke Dimitrov","Stanke Dimitrovo","do~upunitsu~a","du pu ni cha","dupeunicha","dwpnytsa","dwpnyzh","Ντούπνιτσα","Дупница","Дупниця","דופניצה","دوپنیتسا","ドゥプニツァ","杜普尼察","두프니차"),34764,new double[]{42.26667,23.11667}),
    GORNA_ORYAHOVITSA(List.of("GOZ","Gorna Orehovica","Gorna Orehovitsa","Gorna Orehovitza","Gorna Orekhovitsa","Gorna Oriahovica","Gorna Orjakhovica","Gorna Orjechovica","Gorna Oryahovitsa","Gorna Oryakhovitsa","Gorna Oréhovitza","Gorna-Orechowiza","Gorna-Oryekhovitsa","Gorno Oryakhovitsa","Горна Оряховица"),32792,new double[]{43.12778,25.70167}),
    SVISHTOV(List.of("Novae","Novensis Moesia Civitas","Sistov","Sistova","Staklen","Steklen","Sveyestov","Svisclov","Svishhov","Svishtov","Svislova","Svistov","Svišlova","Svištov","Swischtow","Свищов"),32256,new double[]{43.61875,25.35033}),
    SMOLYAN(List.of("Paschmaklii","Pashmakla","Pashmakli","Pashmaklă","Pasmakli","Pasmakly","Pašmakli","Smolian","Smoljan","Smolyan","Смолян"),32069,new double[]{41.57439,24.71204}),
    PETRICH(List.of("Petric","Petrich","Petrich'","Petrici","Petricius","Petricz","Petritch","Petrits","Petritsch","Petritsi","Petritsj","Petritš","Petriç","Petrič","Petričius","Pétritch","bytrytsh","pei te li qi","peteulichi","petorichi","ptrych","ptryz","Πετρίτσι","Петрич","Пєтричь","פטריץ","بيتريتش","پتریچ","ペトリチ","佩特里奇","페트리치"),30308,new double[]{41.39846,23.20702}),
    LOZENETS(List.of("Lozenets","Lozenec","lozenetz","лозенец","лозенетз","Лозенец"),20000,new double[]{42.21108,27.80132}),
    ASPARUHOVO(List.of("Asparuhovo","Asparukhovo","Аспарухово"),27000,new double[]{43.18067,27.88823}),
    SAMOKOV(List.of("Samakov","Samokov","Samokow","Samovkov","Самоков"),26765,new double[]{42.337,23.5528}),
    VARVARA(List.of("Varvara","Варвара"),10000,new double[]{42.11666,27.9166}),
    ARAPYA(List.of("Arapya","Arupya","Arapia","arupia","арапия","арапя"),10000,new double[]{42.17918,27.84588}),
    LOM(List.of("Aligina Makhala","Dzhembek Makhala","Kalen Potok","Lom","Lom Palanka","Nikolaevo","Nikolaewo","Лом"),26594,new double[]{43.82106,23.23677}),
    SANDANSKI(List.of("Sandanski","Sveti Vrac","Sveti Vrach","Sveti Vrač","Sveti-Vratch","Svéti-Vratch","Sweti Wratsch","Xanne Sandanski","Yane Sandanski","Сандански","Свети Врач"),26459,new double[]{41.56667,23.28333}),
    SLUNCHEV_BRIQG(List.of("Slunchev brqg","Slanchev brqg","слънчев","Слънчев Бряг","сл. бряг","сл.бряг","Sunny Beach","Sunnybeach","Sonnenstrand","Слънчака","Сланчака"),10000,new double[]{42.658829, 27.689211}),
    SEVLIEVO(List.of("Savlievo","Seljvi","Selvi","Sevelijevo","Sevlievo","Sevlijevo","Sewliewo","Севлиево"),24582,new double[]{43.02583,25.11361}),
    NOVA_ZAGORA(List.of("Eni Zagra","Ienizagra","Jeni Saghra","Jeni Zagra","Nova Zagora","н.загора","н.загора","Nova-Zagora","Nová Zagora","Nowa Sagora","Nowa Zagora","Yeni Sagra","Yeni Zagra","Yeni Zağra","nobajagola","nwwa zagwra","xin zha ge la","Νόβα Ζαγόρα","Нова Загора","Нова-Загора","נובה זאגורה","نووا زاگورا","نۆڤا زاگۆرا","新扎戈拉","노바자고라"),24340,new double[]{42.48333,26.01667}),
    VELINGRAD(List.of("Velingrad","Velingradas","Velinkrant","Welingrad","bellingeuladeu","vu~eringurato","wei lin ge lei","wlyngrad","Βέλιγκραντ","Велинград","ולינגראד","ولینگراد","ڤێلینگراد","ヴェリングラト","韋林格勒","벨린그라드"),24036,new double[]{42.02754,23.99155}),
    TROYAN(List.of("Comuna Troian","Gmina Trojan","Obshhina Trojan","Troian","Trojan","Troyan Municipality","Troïan","te luo yang shi","Община Троян","Троян","ტროიანის თემი","特羅揚市"),21162,new double[]{42.89427,24.71589}),
    AYTOS(List.of("Aitos","Ajtos","Aytos","Айтос"),20986,new double[]{42.7,27.25}),

    BOTEVGRAD(List.of("Botevgrad","Orchanie","Orhanie","Orhanje","Orkhanie","Ботевград"),20909,new double[]{42.9,23.78333}),
    GOTSE_DELCHEV(List.of("Ano Nevrokopi","Goce Delcev","Goce Delcevas","Goce Delchev","Goce Delczew","Goce Delčev","Goce Delčevas","Goce Dełczew","Goce-Delchev","Gote Delcev","Gotse Delchev","Gotse Deltchev","Gotse Deltsev","Gotse Deltsjev","Gotse Deltšev","Gotsi Delchev","Gotsé Deltchev","Gotze Deltchev","Goze Deltschew","Goțe Delcev","Nevrakop","Nevrekop","Nevrokop","Nevrâkop","Newrokop","ge cai dai er qie fu","gwjh dlchw","gwzh dlz'b","Άνω Νευροκόπι","Гоце Делчев","Гоце-Делчев","Неврокоп","Գոցե Դելչև","גוצה דלצ'ב","گوجه دلچو","ゴツェ・デルチェフ","戈采代爾切夫"),20471,new double[]{41.56667,23.73333}),
    KARLOVO(List.of("Grad Karlove","Karliova","Karlovas","Karlovo","Karlowo","Karlıova","Karłowo","Levskigrad","ka er luo wo","kaleullobo","karlwww","karurovu~o","qrlwbw","Κάρλοβο","Карлово","קרלובו","کارلووو","کارلۆڤۆ","カルロヴォ","卡爾洛沃","카를로보"),19958,new double[]{42.63333,24.8}),
    KARNOBAT(List.of("Karnabat","Karnobat","Karnobatski prokhod","Poljanovgrad","Polyanovgrad","Карнобат","Карнобатски проход"),19709,new double[]{42.65,26.98333}),
    PANAGYURISHTE(List.of("Otalkioj","Otalkiöj","Panaghiourichte","Panaghiourichté","Panaghurichte","Panagiuriste","Panagjurisce","Panagjurischte","Panagjurishhe","Panagjuriste","Panagjurište","Panagjurišče","Panagyurishche","Panagyurishte","Панагюрище"),19389,new double[]{42.49518,24.19021}),
    SVILENGRAD(List.of("Cisri Mustafapasa","Cisri Mustafapaşa","Mustafa-Pasha","Mustafapasa","Mustafapaşa","Slivengrad","Svilen","Svilengrad","Svilengradas","Svilengrade","Swilengrad","aswylngrad","si wei lun ge lei","Свиленград","סבילנגראד","اسویلنگراد","سڤیلێنگراد","斯維倫格勒"),19279,new double[]{41.76667,26.2}),
    HARMANLI(List.of("Charmanlii","Harmanli","Harmanlii","Harmanlu","Harmanly","Harmanlü","Hermanli","Kharmanli","Kharmanlii","Kharmanliy","Харманли"),18931,new double[]{41.93333,25.9}),
    PESHTERA(List.of("Momarsko","Pechtera","Pescera","Peschtera","Peshchera","Peshhera","Peshtera","Pestera","Peštera","Peščera","Пещера"),18676,new double[]{42.03372,24.29995}),
    CHIRPAN(List.of("Chirpan","Cirpan","Tchirpan","Tschirpan","Čirpan","Чирпан"),17243,new double[]{42.2,25.33333}),
    PARVOMAY(List.of("Borisograd","Borisovgrad","Borissograd","Borissovgrade","Borissowgrad","Hadzi Ejles","Hadzi-Eles","Hadzi-Jeiles","Hadži Ejles","Hadži-Eles","Hadži-Jeiles","Khadzhi Eiles","Khadzhi-Eles","Parvomay","Purvomai","Purvomaj","Purvomay","Pŭrvomai","Pŭrvomay","Първомай"),17000,new double[]{42.1,25.21667}),
    POPOVO(List.of("Popkioj","Popkioy","Popkiöj","Popovas","Popovo","Popowo","bo bo wo","pwpwbw","pwpwww  blgharstan","Попово","פופובו","پوپووو، بلغارستان","پۆپۆڤۆ","波波沃"),16571,new double[]{43.35,26.23333}),
    RAKOVSKI(List.of("General Niklaevo","General Nikolaevo","General Nikolaewo","Kalich","Kaliclii","Kaličh","Kaličlii","Kaluchlii","Kaluchliy","Kalŭchlii","Kalŭchliy","Rakovski","Раковски"),15782,new double[]{42.27408,24.94083}),
    BERKOVITSA(List.of("Berkovica","Berkovitsa","Berkovitsa Municipality","Berkovitsay","Berkovitza","Berkowiza","Comuna Berkovita","Comuna Berkovița","Gmina Berkowica","Obshhina Berkovica","Obstina Berkovica","Obština Berkovica","bei er ke wei cha shi","Берковица","Община Берковица","ბერკოვიცის თემი","貝爾科維察市"),15027,new double[]{43.23581,23.12738}),
    RADOMIR(List.of("Radomir","Radomiras","la duo mi er","ladomileu","radomiru","radwmyr","Радомир","ראדומיר","رادومیر","ڕادۆمیر","ラドミル","拉多米爾","라도미르"),14755,new double[]{42.54565,22.96553}),
    KOZLODUY(List.of("Koslodui","Kosloduj","Kozlodouy","Kozlodui","Kozloduj","Kozlodujus","Kozloduy","Kozloudoui","Kozludui","Kozłoduj","ke zi luo du yi","kojeullodu-i","kozloduj","kozurodo~ui","kwzlwdwy","qwzlwdwy","Козлодуй","Козлодуј","козлодуй","קוזלודוי","کوزلودوی","کۆزلۆدوی","コズロドゥイ","科茲洛杜伊","코즐로두이"),14717,new double[]{43.77864,23.72058}),
    RADNEVO(List.of("Radne Machale","Radne Makhle","Radne-Makhala","Radnevo","Radnewo","Раднево"),14667,new double[]{42.3,25.93333}),
    IHTIMAN(List.of("Ichtiman","Ihtiman","Ikhitman","Ikhtiman","Ихтиман"),14154,new double[]{42.43333,23.81667}),
    TRYAVNA(List.of("Treavna","Trevna","Trewna","Triavna","Trjavna","Trjawna","Tryavna","Tryevna","Trěvna","te li ya fu na","toryavuna","trqvna","triqvna","tryavna","tryawna","Трявна","Трјавна","טריאבנה","تریاونا","تریاڤنا","トリャヴナ","特里亞夫納"),13818,new double[]{42.86667,25.5}),
    PROVADIA(List.of("Pravodi","Provadia","Provadidija","Provadija","Provadiya","Prowadija","Провадия"),13755,new double[]{43.18333,27.43333}),
    POMORIE(List.of("Ahiolo","Akhillo","Akhilu","Akhiolo","Anchialo","Anchialos","Anchijelo","Anchilejo","Anhialo","Anhiolo","Ankhelu","Ankhelú","Ankhialo","Ankhiolo","Pamorye","Pomorie","Pomorije","Pomorijė","Pomoriye","Pomorié","Pomorye","bo mo lai","pomorie","pwmwryh","Αγχίαλος","Паморые","Поморие","Поморије","Поморіє","پوموریه","پۆمۆریێ","ポモリエ","波摩萊"),13714,new double[]{42.56326,27.62986}),
    BYALA_SLATINA(List.of("Bela Slatina","Biela Slatina","Bjala Slatina","Bjela Slatina","Byala Slatina","Byela-Slatina","Бяла Слатина"),13307,new double[]{43.46667,23.93333}),
    NOVI_PAZAR(List.of("Eni Bazar","Eni Pazar","Jenibazar","Novi Pazar","Novi-Paza","Nowi Pasar","Нови Пазар"),13276,new double[]{43.35,27.2}),
    BALCHIK(List.of("Balchik","Balchiq","Balcic","Baltchik","Baltschik","Балчик","Bulchik"),13000,new double[]{43.42166,28.15848}),
    CHERVEN_BRYAG(List.of("Cerven-Breg","Cherven brjag","Cherven-Breg","Cherven-Bryeg","Cherveni Bryag","Cherveni-Bjerg","Tcherven Bryag","Tscherwen Breg","Červen-Brěg","Червен бряг"),13000,new double[]{43.27884,24.08251}),
    RAZLOG(List.of("Mahomia","Mehomia","Mekhomija","Mekhomiya","Pazlog","Raslog","Raslug","Razlog","Razlogas","Razłog","la zi luo ge","razlwg","razlwgh","razuroku","rzlwg","Мехомија","Разлог","רזלוג","رازلوغ","رازلوگ","ラズロク","拉茲洛格"),12486,new double[]{41.8863,23.46714}),
    PAVLIKENI(List.of("Pavlikem","Pavlikene","Pavlikeni","Pavlikeniai","Pawlikeni","pa fu li kai ni","pavurikeni","pawlykny","Павликени","پاولیکنی","پاڤلیکێنی","パヴリケニ","帕夫利凱尼"),12214,new double[]{43.24278,25.32194}),
    KOSTINBROD(List.of("Kostinbrod","Костинброд"),12175,new double[]{42.81667,23.21667}),
    STAMBOLIYSKI(List.of("Gara Krichim","Krichim","Novi Krichim","Stambolijski","Stamboliyski","Stamoboliyski","Стамболийски"),12070,new double[]{42.13333,24.53333}),
    MEZDRA(List.of("Mesdra","Mezdra","Mezhdra","Mizara","mei zi de la","mezudora","myzdra","mzdra","Мездра","مزدرا","ميزدرا","مێزدرا","メズドラ","梅茲德拉"),11975,new double[]{43.15,23.7}),
    LEVSKI(List.of("Kara Agach","Levski","Lewski","Turski Karaagach","Левски"),11467,new double[]{43.36667,25.13333}),
    KAVARNA(List.of("Cavarna","Kavarna","Kawarna","Каварна"),11205,new double[]{43.43601,28.33953}),
    ELHOVO(List.of("Elchovo","Elchowo","Elhovo","Elkhovo","Kasul-Agac","Kazul-Agach","Kazŭl-Agach","Kizilagac","Kizilagač","Kuzul Indzhe","Kuzul-Agach","Kăsŭl-Agač","Kŭzŭl Indzhe","Kŭzŭl-Agach","Елхово"),11107,new double[]{42.16667,26.56667}),
    ETROPOLE(List.of("Etropole","Etropolje","Etropolė","Jetropole","ai te luo bo lai","atrwpwlh","Єтрополе","Јетропоље","Етрополе","אטרופולה","ئێترۆپۆلێ","اتروپوله","埃特羅波萊"),11031,new double[]{42.83333,24.0}),
    TETEVEN(List.of("Teteven","Tetevene","Tetewene","Тетевен"),10790,new double[]{42.91667,24.26667}),
    TUTRAKAN(List.of("Turtucaia","Turtukai","Tutrakan","Tutrakanas","Tutrakhan","tu te la kan","twtrakan","Тутракан","טוטראקן","توتراکان","圖特拉坎"),10022,new double[]{44.04906,26.61206}),
    LUKOVIT(List.of("Gorni Lukovit","Loukovit","Lukovit","Lukowit","Луковит"),9792,new double[]{43.2,24.16667}),
    BELENE(List.of("Beleke","Belene","Belina","Bjelene","Byelene","Белене"),9781,new double[]{43.64594,25.12627}),
    ZLATNI_PYASATSI(List.of("Golden Sands","Goldstrand","Zlatni pjasuci","Zlote Piaski","Zolotye Peski","Złote Piaski","Златни пясъци","Золотые Пески"),9760,new double[]{43.285,28.0418}),
    ISPERIH(List.of("Isperich","Isperih","Isperikh","Kemallar","Kemanlar","Исперих"),9735,new double[]{43.71667,26.83333}),
    SREDETS(List.of("Grudovo","Kara-Bunar","Sradets","Sredec","Sredets","Sredetz","Sredez","Sryedets","Srědec","Средец"),9573,new double[]{42.34747,27.17898}),
    VELIKI_PRESLAV(List.of("Eski Stambid","Eski Stambolluk","Eski-Stambul","Preslav","Preslaw","Prieslav","Prjeslav","Veliki Preslav","Weliki Preslaw","Weliki Presław","Велики Преслав"),9425,new double[]{43.16667,26.81667}),
    BANSKO(List.of("Banjska","Banjsko","Bans'ko","Banskas","Bansko","Banysko","ban si ke","banseuko","banskw","bansuko","bnsqw","Μπάνσκο","Банско","Бансько","Բանսկո","בנסקו","بانسکو","バンスコ","班斯科","반스코"),9232,new double[]{41.8383,23.48851}),
    OMURTAG(List.of("Omortag","Omurtag","Osman-Pazar","Osmanbazar","Омуртаг"),9070,new double[]{43.1,26.41667}),
    KUBRAT(List.of("Balbunar","Kubrat","Кубрат"),8980,new double[]{43.79658,26.50063}),
    SVOGE(List.of("Svogbe","Svoge","Svoghe","Svoghé","Svogja","Svogje","Swoge","Своге"),8964,new double[]{42.96667,23.35}),
    KRICHIM(List.of("Krichim","Kricim","Kricima","Krinchim","Kritchim","Kritschim","Krizim","Kričim","Kričima","Križim","Kroma","Кричим"),8580,new double[]{42.05,24.46667}),
    LYASKOVETS(List.of("Leskovec","Leskovets","Leskovetz","Leskovètz","Leskowez","Ljaskovec","Ljeskovec","Lyaskovets","Lyaskovetz","Lyeskovets","Lěskovec","Лясковец"),8488,new double[]{43.11111,25.72833}),
    GULUBOVO(List.of("Duvadzhizliy","Galab","Galabovo","Galob","Galöb","Gelub","Gilib","Gulab","Gulub","Gulubovo","Gălăb","Gŭlăb","Gŭlŭb","Gŭlŭbovo","Kum Duvandzhii","Гълъбово"),8400,new double[]{42.13333,25.85}),
    RAKITOVO(List.of("Rakitovo","Rakitowo","Ракитово"),8376,new double[]{41.99012,24.0873}),
    DRYANOVO(List.of("Drenova","Drenovo","Drenowo","Drjanovo","Drjenovo","Dryanovo","Drěnovo","Дряново"),8346,new double[]{42.97897,25.4785}),
    DEVNYA(List.of("Devne","Devnja","Devnya","Dewnja","Девня"),8171,new double[]{43.22222,27.56944}),
    PIRDOP(List.of("Pirdop","pi er duo pu","pyrdwp","Пирдоп","پیردوپ","پیردۆپ","皮爾多普"),8136,new double[]{42.7,24.18333}),
    LYUBIMETS(List.of("Khebibchevo","Lioubimetz","Ljubimec","Ljubimetz","Ljubimez","Lyubimets","Lyubimetz","Любимец"),8065,new double[]{41.83333,26.08333}),
    BELOSLAV(List.of("Belevo","Belewo","Beloslav","Beloslaw","Belovo","Bielevo","Bjelevo","Byelevo","Gebedze","Gebedzhe","Gebedže","Белослав"),7989,new double[]{43.1896,27.70429}),
    HISARYA(List.of("Banja","Banya","Chissar","Hisar","Hisar Kjuselere","Hisarya","Hissar","Husar","Khisar","Khisar-Kyuselere","Khisar-Momina Banya","Khisarja","Khisarya","Khiskeseleri","Momina-Banja","Momina-banya","Хисаря"),7903,new double[]{42.5,24.7}),
    GENERAL_TOSHEVO(List.of("Casim","General Tosevo","General Toshevo","General Toševo","General-Toshevo","Ion Gheorghe Duca","Kasamkioi","Kassalkioi","Kassălkioi","Kasum","Kasumk'oy","Kasŭm","Kasŭmk’oy","Malovets","Mamucichioi","Momuch-K'oy","Momuch-K’oy","Mumdshikioi","Генерал Тошево","Генерал-Тошево"),7758,new double[]{43.70123,28.03787}),
    SLIVNITSA(List.of("Slivica","Slivnica","Slivnitsa","Slivnitza","Sliwniza","Сливница"),7545,new double[]{42.85182,23.03792}),
    VARSHETS(List.of("Varshets","Varshetz","Vershets","Vresec","Vrešec","Vrsec","Vrshets","Vršec","Vursec","Vurshec","Vurshets","Vuršec","Vărshets","Vŭrshets","Warschez","Wărschez","Вършец"),7512,new double[]{43.19356,23.2868}),
    DEVIN(List.of("D'ovlen","Devin","Devine","Dewin","Djovlen","Dyevin","Děwin","dai wen","dwwyn","dwyn  blgharstan","Девин","דווין","دوین، بلغارستان","دێڤین","代溫"),7393,new double[]{41.74327,24.40003}),
    SIMEONOVGRAD(List.of("Maritsa","Seimen","Sejmen","Semenli","Seymen","Simeonovgrad","Симеоновград"),7388,new double[]{42.03333,25.83333}),
    ELIN_PELIN(List.of("Elin Pelin","Novoselci","Novoseltsi","Novosseltzi","Nowosselzi","Vlavo Trichkov","Елин Пелин"),7373,new double[]{42.66667,23.6}),
    ZLATOGRAD(List.of("Dara-Dere","Daridere","Dară-Dere","Darıdere","Slatograd","Zlatograd","Zlatograde","Zlatonkrant","Zlatoqrad","Złatograd","zi la tuo ge lei","zlatwgrad","Ζλάτογκραντ","Златоград","זלאטוגרד","زلاتوگراد","زلاتۆگراد","茲拉托格勒"),7331,new double[]{41.3795,25.09605}),
    DOLNI_CHIFLIK(List.of("Dolen Chiflik","Dolen Tchiflik","Dolni Chifl","Dolni Chiflik","Dolni Chiftlik","Dolni Ciflik","Dolni Tchiftlik","Dolni chiflik","Dolni Čiflik","Dolni-Chnflik","Dolni-Tschiflik","Dolèn Tchiflik","Georgi Traykov","Долни Чифлик","Долни чифлик"),7169,new double[]{42.99296,27.71596}),
    AKSAKOVO(List.of("Adzemler","Adzhemler","Adžemler","Aksakov","Aksakovo","Aksakovo Municipality","Aksakowo","Comuna Aksakovo","Gmina Aksakowo","Obshhina Aksakovo","a ke sa ke wo shi","aksakaww","Аксаково","Община Аксаково","اکساکاوو","აკსაკოვოს თემი","阿克薩科沃市"),7132,new double[]{43.25615,27.82105}),
    KNEZHA(List.of("Kneja","Knesha","Kneza","Knezha","Kneža","Knizha","Knjeza","Knježa","Knyazha","Кнежа"),6889,new double[]{43.5,24.08333}),
    TERVEL(List.of("Comuna Tervel","Curt Bunar","Curtburnar","Dshami Machala","Gmina Terwel","Gmina Terweł","Kurt Bunar","Municipio de Tervel","Município de Tervel","Obshhina Tervel","Tervel","Tervel Municipality","tai er wei er shi","Община Тервел","Тервел","ტერველის თემი","泰爾韋爾市"),6808,new double[]{43.74789,27.40911}),
    DULOVO(List.of("Acadanlar","Accadanlar","Accadânlar","Ak-Kadunlar","Ak-Kadŭnlar","Akkadanlar","Dulovo","Dulowo","Inatra-Mahle","Дулово"),6788,new double[]{43.81667,27.15}),
    SIMITLI(List.of("Izvoritye","Izworit","Simeti","Simetli","Simetlu","Simetlü","Simitle","Simitli","Simitlii","Simitly Gare","Симитли"),6729,new double[]{41.88333,23.11667}),
    TVARDITSA(List.of("Tvardica","Tvarditsa","Tvarditza","Tverditsa","Tvrdica","Tvrditsa","Tvurdica","Tvurditsa","Tvŭrdica","Tvŭrditsa","Twardiza","Twărdiza","Твърдица"),6519,new double[]{42.7,25.9}),
    TOPOLOVGRAD(List.of("Kavakli","Kavaklii","Kavakly","Topolovgrad","Topolovgrade","Topolowgrad","Topołowgrad","tuo bo luo fu ge lei","twpwlwfgrad","Тополовград","توپولوفگراد","تۆپۆلۆڤگراد","托波洛夫格勒"),6464,new double[]{42.08333,26.33333}),
    SAEDINENIE(List.of("Golemo Konare","Goljamo Konare","Goljemo Konare","Goljemo Konari","Golyamo Konare","Golyemo-Konare","Saedinenie","Suedinenie","Sŭedinenie","Съединение"),6427,new double[]{42.26667,24.55}),
    KOTEL(List.of("Kazan","Kotel","Котел"),6421,new double[]{42.88333,26.45}),
    NESEBAR(List.of("Mesembria","Mesembrija","Mesemvria","Mesemvrija","Mesemvriya","Messemvria","Messemvrija","Messemwria","Misevrin","Misivri","Misivria","Missevriya","Nesebar","Neseber","Neseberas","Nesebr","Nesebur","Nesebyr","Nesebâr","Nesebăr","Nesebŭr","Nesempar","Nessebar","Nessebur","Nessebăr","Nessèbar","Neszebar","Njasebyr","Nеsebăr","nei sai bo er","nesebaru","nesebeoleu","nesebiri","nsbar","nsbr","nysybar","Νέσεμπαρ","Месембрія","Несебар","Несебр","Несебър","Несебыр","Нясебыр","נסבר","نسبار","نيسيبار","نێسێبار","ნესებირი","ነሰብር","ネセバル","内塞伯爾","네세버르"),6302,new double[]{42.65921,27.73602}),
    BOBOV_DOL(List.of("Bobor-Dol","Bobov Dol","Bobov-Dol Mina","Bobovdol","Bobow Dol","Бобов Дол","Бобовдол"),6184,new double[]{42.36256,23.00324}),
    TSAREVO(List.of("Carevo","Michurin","Tsarevo","Tsarévo","Tzarevo","Vasiliko","Zarewo","Царево","Лозенец"),6085,new double[]{42.16955,27.84541}),
    ELENA(List.of("Elena","Jelena","ai lun na","alna  blgharstan","erena","Елена","אלנה","ئێلێنا","النا، بلغارستان","エレナ","埃倫娜"),6042,new double[]{42.93333,25.88333}),
    YAKORUDA(List.of("Jakoruda","Johurut","Jokoruda","Yakoruda","Yokoruda","Якоруда"),6008,new double[]{42.02528,23.68417}),
    STRALDZHA(List.of("Straldsha","Straldza","Straldzha","Straldža","Стралджа"),5817,new double[]{42.6,26.68333}),
    ZLATITSA(List.of("Slatiza","Zlatica","Zlatitsa","Zlatitza","Zlatiza","Златица"),5786,new double[]{42.71667,24.13333}),
    STRAZHITSA(List.of("Kada K'oy","Kada K’oy","Kadikioy","Strajitsa","Strajitza","Strashiza","Strazhica","Strazhitsa","Strazica","Stražica","Стражица"),5728,new double[]{43.23333,25.96667}),
    ORYAHOVO(List.of("Orechovo","Orechowo","Orehovo","Orejekhovo","Orekhovo","Orjahovo","Orjakhovo","Orjechovo","Orjekhovo","Oryahovo","Oryakhovo","Oryekhovo","Rachowo","Rahova","Rakovo","Ruhovo","Оряхово"),5706,new double[]{43.73618,23.96052}),
    BELOGRADCHIK(List.of("Belogradchik","Belogradcik","Belogradtchik","Belogradtgchik","Bjelogradcik","Bjelogradčik","Byelogradchik","Bélogradtchik","Bělogradčik","Белоградчик"),5688,new double[]{43.62722,22.68361}),
    POLSKI_TRAMBESH(List.of("Polsk Trumbesh","Polsk Trŭmbesh","Polski Trambech","Polski Trambesh","Polski Trembes","Polski Trembeš","Polski Trumbesh","Polski Trŭmbesh","Polski-Trambesch","Polski-Trembesh","Polski-Trămbesch","Trembesh","Полски Тръмбеш"),5663,new double[]{43.37233,25.63525}),
    MADAN(List.of("Madan","Мадан"),5661,new double[]{41.49869,24.93973}),
    CHEPELARE(List.of("Cepelare","Chepelare","Chepelari","Czepelare","Czepełare","Tchepelare","Tjepelare","Tschepelare","Tsepelare","Tsjepelare","Tšepelare","cheperare","chplarh","qie pei la lei","Čepelare","Чепеларе","چپلاره","چێپێلارێ","チェペラレ","切佩拉雷"),5478,new double[]{41.73333,24.68333}),
    PERUSHTITSA(List.of("Perishchitsa","Peruschtiza","Perushchitsa","Perushhica","Perushtitsa","Perustica","Peruštica","Перущица"),5350,new double[]{42.05,24.55}),
    DALGOPOL(List.of("Dalgopol","Delgopol","Dulgopol","Dŭlgopol","Novo-Selo","Дългопол"),5272,new double[]{43.05,27.35}),
    KRUMOVGRAD(List.of("Koshu-Kavak","Kosikavak","Kossukavak","Kossukovak","Kosu-Kavak","Košu-Kavak","Kroumovgrade","Krumovgrad","Krumowgrad","Крумовград"),5271,new double[]{41.47127,25.65485}),
    DOLNI_DABNIK(List.of("Diubnik","Dolni Dabnik","Dolni Dibnik","Dolni Dobnik","Dolni Dubnik","Dolni Döbnik","Dolni Dăbnik","Dolni Dŭbnik","Dolni-Debnik","Dolni-Dubnjak","Долни Дъбник"),5259,new double[]{43.4,24.43333}),
    VALCHEDRAM(List.of("Valchedarma","Valchedram","Valtchedram","Valtchidarma","Vlcdrma","Vlcedrama","Vlcedrma","Vlchedrma","Vlcidrama","Vlčdrma","Vlčedrama","Vlčedrma","Vlčidrama","Vulcedurma","Vulchedrum","Vulchedurma","Vălchedărma","Vŭlchedrŭm","Vŭlchedŭrma","Vŭlčedŭrma","Waltschedrama","Waltschedrăma","Вълчедръм"),5207,new double[]{43.69281,23.44518}),
    VETOVO(List.of("Vetova","Vetovo","Vjetevo","Vyetovo","Wetowo","Ветово"),5175,new double[]{43.7,26.26667}),
    GODECH(List.of("Glotnitsa","Godec","Godech","Godetch","Godetsch","Godeč","Molak","Negolova","Staro Selo","Stoykina","Trap","Yovkina","Годеч"),5154,new double[]{43.01682,23.04852}),
    NEDELINO(List.of("Nedelino","Nedelio","Nedyelino","Uzendere","Uzun-Dere","Неделино"),5017,new double[]{41.45602,25.08008}),
    DOLNA_BANYA(List.of("Banja","Dolna Bania","Dolna Banja","Dolna Banya","Долна Баня"),4990,new double[]{42.3,23.76667}),
    KAMENO(List.of("Kaiali","Kajali","Kajalii","Kajalu","Kajalü","Kameno","Kayalii","Kayaliy","Kayalu","Kayalŭ","Kayliy","Камено"),4952,new double[]{42.57084,27.29875}),
    SLAVYANOVO(List.of("Slavianovo","Slavjanovo","Slavyanovo","Slawjanowo","Trastenik","Trstenik","Trustenik","Trăstenik","Trŭstenik","Turska Trestenik","Turski Trustenik","Turski Trŭstenik","Славяново"),4793,new double[]{43.46667,24.86667}),
    SAPAREVA_BANYA(List.of("Gorna Banja","Gorna-Bania","Gorna-Banya","Sapareva Banja","Sapareva Banya","Сапарева Баня"),4610,new double[]{42.28333,23.26667}),
    BRATSIGOVO(List.of("Bracigovo","Bratsigovo","Bratzigovo","Brazigowo","Брацигово"),4577,new double[]{42.01667,24.36667}),
    SUVOROVO(List.of("Kozludza","Kozludzha","Kozludža","Novgradets","Nowgradez","Suvorovo","qwzlwjh","qwzlyjh","Суворово","قوزلوجه","قوزلیجه"),4563,new double[]{43.33058,27.59908}),
    STRELCHA(List.of("Strelca","Strelcha","Streltscha","Strelča","Strjelca","Strjelča","Stryelcha","Стрелча"),4545,new double[]{42.5,24.31667}),
    DVE_MOGILI(List.of("Damogila","Dbb Mogili","Dve Mogili","Dve mogili","Dwe Mogili","Две Могили","Две могили"),4526,new double[]{43.59258,25.87486}),
    SOZOPOL(List.of("Apollonia","Sizebolu","Sizopol","Sosopol","Sozopol","Sozopol'","Sozopole","Sozopolis","sozoporu","suo zuo bo er","swzwpwl","Σωζόπολη","Созопол","Созополь","סוזופול","سوزوپول","سۆزۆپۆل","ソゾポル","索佐波爾"),4500,new double[]{42.41801,27.6956}),
    DEBELETS(List.of("Debebletz","Debelec","Debelet","Debelets","Debeletz","Debelez","Deblec","Débéblètz","Дебелец"),4418,new double[]{43.03333,25.61667}),
    PRAVETS(List.of("Pravec","Pravets","Pravetz","Prawez","Правец"),4400,new double[]{42.88333,23.91667}),
    BOZHURISHTE(List.of("Bojurishe","Boshurischte","Bozhurishhe","Bozhurishte","Божурище"),4360,new double[]{42.75,23.2}),
    ISKAR(List.of("Iskar","Iskur","Iskŭr","Machalata","Machlata","Machluta","Machlüta","Mahalata","Mahlata","Makhalata","Makhlata","Pelovo","Искър"),4329,new double[]{43.45,24.26667}),
    SMYADOVO(List.of("Smedovo","Smedowo","Smjadovo","Smjedovo","Smyadovo","Smyedovo","Смядово"),4231,new double[]{43.06667,27.01667}),
    BELOVO(List.of("Beljovo","Belovo","Gara Bel'oro","Gara Bel’oro","Gara Byelovo","Белово"),4155,new double[]{42.21239,24.02081}),
    NIKOPOL(List.of("Nicopol","Nicopoli","Nicopolis","Nicòpol","Nigbolu","Nikapoly","Nikopil","Nikopol","Nikopoli","Nikápoly","Niğbolu","ni ke bo er","nikopol","nikoporu","nykwpwl  blgharstan","nyqwpwl","Никопол","Никопољ","Нікопол","ניקופול","نیکوپول، بلغارستان","نیکۆپۆل، بولگاریا","ニコポル","尼科波尔","니코폴"),4137,new double[]{43.70528,24.89521}),
    KRESNA(List.of("Bahnhof Pirin","Gara Pirin","Kresna","Krésna","ke lei si na","krsna","kuresuna","Кресна","Крѣсьна","Կրեսնա","کرسنا","کرێسنا","クレスナ","克雷斯納"),4117,new double[]{41.73333,23.15}),
    BREZNIK(List.of("Berznik","Bresnik","Breznik","Brjeznik","Bryeznik","Obshtina Breznik","Obsjtina Breznik","brznyk","bu lei zi ni ke","burezuniku","Брезник","برزنیک","برێزنیک","ブレズニク","布雷茲尼克"),4004,new double[]{42.74085,22.90723}),
    TSAR_KALOYAN(List.of("Car Kalojan","Khlebarovo","Torlak","Torlaki","Tsar Kaloyan","Tsar Kaloyanovo","Turlak","Tzar Kaloyan","Zar Kalojan","Цар Калоян"),3994,new double[]{43.61667,26.25}),
    IVAYLOVGRAD(List.of("Ivailovgrad","Ivajlovgrad","Ivatlovgrade","Ivaylovgrad","Ivaïlovgrad","Iwailowgrad","Iwajlowgrad","Iwajłowgrad","Orta-K'oy","Orta-Keui","Orta-Kioi","Orta-Kioj","Orta-Kioï","Orta-Kiöj","Orta-Kyoy","Orta-K’oy","Ortakoey","Ortakoi","Ortaköi","Ortaköy","Ortokoj","Ortoköj","aywalwfgrad","yi wa yi luo fu ge lei","Івайловград","Ивайловград","Ивајловград","ئیڤایلۆڤگراد","ایوالوفگراد","伊瓦伊洛夫格勒"),3969,new double[]{41.52672,26.1249}),
    BATAK(List.of("Batak","ba ta ke","batak","batak  blgharstan","bataku","Батак","باتاک","باتاک، بلغارستان","バタク","巴塔克"),3917,new double[]{41.94225,24.21843}),
    SHABLA(List.of("Sabla","Shabla","Şabla","Шабла"),3901,new double[]{43.53983,28.53429}),
    SVETI_VLAS(List.of("Manasturkioy","Manastŭrkioy","Monasturkioy","Monastŭrkioy","Saint Vlas","St. Vlas","Sveti Vlas","Sveti-Vlas","Sweti Wlas","Vlas","Влас","Свети-Влас"),3875,new double[]{42.7136,27.75867}),
    APRILTSI(List.of("Aprilci","Apriltzi","Априлци"),3851,new double[]{42.84142,24.91759}),
    SUNGURLARE(List.of("Sungulare","Sungulari","Sungurlar","Sungurlare","Sungurlari","Сунгурларе"),3834,new double[]{42.76667,26.78333}),
    DRAGOMAN(List.of("Dragoman","Драгоман"),3814,new double[]{42.92191,22.93109}),
    VARBITSA(List.of("Varbitsa","Virbica","Vrbica","Vrbitsa","Vurbica","Vurbitsa","Vărbitsa","Vŭrbitsa","Warbiza","Wărbiza","Върбица"),3803,new double[]{43.0,26.63333}),
    RUDOZEM(List.of("Chervenkovgrad","Palas","Palaz","Roodozem","Rudosem","Rudozem","Рудозем"),3783,new double[]{41.48751,24.84945}),
    KULA(List.of("Adlijo","Adlye","Koula","Kula","Кула"),3738,new double[]{43.88833,22.52139}),
    MIZIA(List.of("Buk'ovtsi","Bukiowzi","Bukyuvtsy","Buk’ovtsi","Mizia","Mizija","Miziya","Мизия"),3712,new double[]{43.68623,23.85371}),
    VALCHIDOL(List.of("Kurt Dere","Valchi Dol","Valchidol","Valci Dol","Vulchidol","Vŭlchidol","Vǎlči Dol","Waltschi Dol","Вълчидол"),3697,new double[]{43.4,27.55}),
    KRIVODOL(List.of("Krivdol","Krivodol","Krivodolska Makhala","Kriwodol","Криводол"),3651,new double[]{43.37444,23.48444}),
    MAGLIZH(List.of("Maglis","Maglish","Magliz","Maglizh","Magliš","Magliž","Meglish","Meglizh","Mglij","Moglic","Moglis","Moglič","Muglish","Mugliz","Muglizh","Mögliš","Măglish","Măglizh","Mŭglish","Mŭglizh","Mŭgliž","Мъглиж"),3643,new double[]{42.6,25.55}),
    KASPICHAN(List.of("Bahnhof Kaspitschan","Gara Kaspican","Gara Kaspichan","Gara Kaspičan","Kaspichan","Kaspitchan","Kaspitchan Gare","Stantsiya Shumlaroad","Каспичан"),3635,new double[]{43.31667,27.16667}),
    ZAVET(List.of("Sawet","Zavet","Zavjet","Zavot","Zavut","Zavyet","Завет"),3589,new double[]{43.76036,26.68063}),
    GULYANTSI(List.of("Galyantsi","Golenci","Guleanci","Guljanci","Guljanzi","Gulyanitsa","Gulyantsi","Гулянци"),3589,new double[]{43.64109,24.69368}),
    STARA_KRESNA(List.of("Kresna","Stara Kresna","Стара Кресна"),3586,new double[]{41.8,23.18333}),
    ROMAN(List.of("Roman","Роман"),3571,new double[]{43.15,23.91667}),
    ARDINO(List.of("Ardino","Egridere","Eğridere","Iridere","Irideré","Khadzhi K'oy","Khadzhi K’oy","a er di nuo","ardino","ardynw","arudino","Ардино","آردینو","ئاردینۆ","არდინო","アルディノ","阿爾迪諾"),3531,new double[]{41.58333,25.13333}),
    LETNITSA(List.of("Letnica","Letnitsa","Letnitza","Letniza","Lietnica","Lyetnitsa","Lětnica","Летница"),3528,new double[]{43.31167,25.07333}),
    DOLNA_MITROPOLIA(List.of("Dolishnja Mitropolija","Dolna Metropolja","Dolna Mitropolia","Dolna Mitropolija","Dolna Mitropoliya","Dolna Netropol Mitropoliya","Dolna-Mitropolija","Dona Mitropolija","PVN","doruna・mitoroporiya","dwlna mytrwpwlya","xia mi te luo bo li ya","Долна Митрополия","Долна-Митрополия","Долішня Митрополія","Доња Митрополија","دولنا میتروپولیا","ドルナ・ミトロポリヤ","下米特羅波利亞"),3479,new double[]{43.46667,24.53333}),
    DUNAVTSI(List.of("Dunavci","Dunavtsi","Dunavtzi","Дунавци"),3371,new double[]{43.92111,22.82111}),
    MALKO_TARNOVO(List.of("Malko Tarnovo","Malko Tarnowo","Malko Turnovo","Malko Tŭrnovo","Malko-Tarnov","Malko-Tirnovo","Malko-Trnovo","Malko-Tărnov","Malkotirnova","Tirnovo","Малко Търново","Търново","turnavo","tarnavo"),3336,new double[]{41.97958,27.52477}),
    DZHEBEL(List.of("Djebel","Dzhebel","Shekh-Dzhumaya","Sheykh-Dzhumaya","Джебел"),3329,new double[]{41.49566,25.30363}),
    SARAFOVO(List.of("Antim I","Paparos","Papure","Sarafovo","Sarefovo","Сарафово"),3290,new double[]{42.56079,27.52195}),
    BUHOVO(List.of("Buchowo","Buhovo","Bukhovo","Бухово"),3283,new double[]{42.76667,23.56667}),
    LAKI(List.of("Laki","Luki","Lŭki","Лъки"),3258,new double[]{41.85,24.81667}),
    SLIVO_POLE(List.of("Kashikler","Kaya Makhle","Slivitsa","Slivo Pole","Sliwiza","Sliwo Pole","Сливо Поле"),3252,new double[]{43.94248,26.20464}),
    KALOFER(List.of("Kalofer","Kaloter","Калофер"),3248,new double[]{42.61667,24.98333}),
    YABLANITSA(List.of("Ablanitsa","Iablanica","Jablanica","Jablaniza","Jablonica","Yablanitsa","Ябланица"),3237,new double[]{43.03139,24.11278}),
    PAVEL_BANYA(List.of("Banya","Ludzha Ali","Ludzha K'oy","Lŭdzha Ali","Lŭdzha K’oy","Pavel","Pavel Banja","Pavel Banya","Pawel","Павел Баня"),3212,new double[]{42.6,25.2}),
    HADZHIDIMOVO(List.of("Dolna-Singartiya","Dolno-Singartiya","Hadzhidimovo","Khadzhidimovo","Shostowo","Zhostovo","Хаджидимово"),3167,new double[]{41.52222,23.86861}),
    BELITSA(List.of("Belica","Belicja","Belita","Belitsa","Belitso","Belitza","Beliza","Belița","Bjelica","Blitsa","Byelitsa","Bělica","bei li cha","blytsa","bylytsa","Белица","Белиця","Բելիցա","بلیتسا","بيليتسا","بێلیتسا","貝利察"),3166,new double[]{41.95694,23.5725}),
    NIKOLAEVO(List.of("Eshekchii","Eshekii","Nikolaevo","Nikolaewo","Nikolajevo","Николаево"),3160,new double[]{42.63333,25.8}),
    TRAN(List.of("Tran","Tren","Trin","Trn","Trun","Trăn","Trŭn","Трън"),3102,new double[]{42.83528,22.65167}),
    BORINO(List.of("Boriio","Borino","Kara-Bulak","Борино"),3084,new double[]{41.68408,24.293}),
    BYALA_CHERKVA(List.of("Bela Cerkva","Bela Cherkva","Bela Tscherkwa","Bela-Cerkova","Bela-Tchekva","Bela-Čerkova","Bjala cherkva","Bjela-Cerkova","Bjela-Cerkva","Bjela-Čerkova","Byala Cherkova","Byala Cherkva","Byela Cherkva","Byela-Cherkova","Béla-Tchekva","Běla Čerkva","Gorni Turcheta","Бяла черква"),3010,new double[]{43.2,25.3}),
    RILA(List.of("Rila","Rila Selo","Riloselo","Рила"),3002,new double[]{42.13333,23.13333}),
    OPAKA(List.of("Opaka","Опака"),3002,new double[]{43.45,26.16667}),
    LOZNITSA(List.of("Kobadin","Kobadun","Kobadŭn","Kubadin","Losniza","Lozitsa","Loznica","Loznitsa","Лозница"),2971,new double[]{43.36667,26.6}),
    UGARCHIN(List.of("Ugarchin","Ugarcin","Ugartschin","Ugarčin","Ugirkin","Ugrchin","Ugrcin","Ugrčin","Ugurchin","Ugurcin","Ugürčin","Ugărchin","Ugărtschin","Ugŭrchin","Угърчин"),2965,new double[]{43.1,24.41667}),
    BOROVAN(List.of("Borovan","Borowan","Борован"),2941,new double[]{43.43333,23.75}),
    KOYNARE(List.of("Koinare","Kojnare","Koynare","Койнаре"),2926,new double[]{43.35,24.13333}),
    BREGOVO(List.of("Bregovo","Bregowo","Brjegovo","Bryagovo","Bryegovo","Брегово"),2892,new double[]{44.15167,22.6425}),
    GURKOVO(List.of("Dimo Makhle","Dimovtsi","Dimowzi","Dumovtsu Razvalina","Dŭmovtsŭ Razvalina","General Gurkovo","Gurkovo","Gurkowo","Khainboaz","Khainito","Khainkioy","Kolupchii","Гурково"),2889,new double[]{42.66667,25.8}),
    KOPRIVSHTITSA(List.of("Avrat Alan","Koprivchtitsa","Koprivcica","Koprivichtitza","Koprivscica","Koprivshchitsa","Koprivshhica","Koprivshtica","Koprivshticja","Koprivshtitsa","Koprivsjtitsa","Koprivstica","Koprivstico","Koprivstita","Koprivčica","Koprivŝtico","Koprivštica","Koprivščica","Koprivștița","Kopriwschtiza","Kopriwsztica","ke pu li fu shen di cha","kopeulipeusyuticha","kopurifushititsu~a","kwpryfshtytsa","qwprybstyzh","Копривштица","Копривштиця","Копривщица","קופריבשטיצה","کوپریفشتیتسا","کۆپریفشتیتسا","コプリフシティツァ","科普里夫什蒂察","코프리프슈티차"),2885,new double[]{42.63333,24.35}),
    KOCHERINOVO(List.of("Kocarinovo","Kocerinovo","Kocherinobo","Kocherinovo","Kocheripovo","Kotcherinovo","Kotscherinowo","Kočarinovo","Kočerinovo","Кочериново"),2872,new double[]{42.08439,23.0571}),
    PARVOMAYTSI(List.of("Parvomaytsi","Purvomajci","Purvomaytsi","Pŭrvomaytsi","Sergjuvec","Temnisko","srghwfchh","Първомайци","Сергювец","Темниско","سرغوفچه"),2867,new double[]{43.15,25.65}),
    DOSPAT(List.of("Dospad","Dospat","Доспат"),2802,new double[]{41.64462,24.15857}),
    PRIMORSKO(List.of("Kjuprija","Kyupriya","Primorsko","Приморско"),2798,new double[]{42.26791,27.75611}),
    KALOYANOVO(List.of("Kalojanovo","Kalojanowo","Kaloyanovo","Seldzhikovo","Seldzikovo","Seldžikovo","Калояново"),2782,new double[]{42.35,24.73333}),
    MEDKOVETS(List.of("Medkovec","Medkovets","Medkovetz","Metkovec","Metkovets","Metkowez","Медковец"),2690,new double[]{43.62403,23.16876}),
    YAKIMOVO(List.of("Jakimovo","Kotenovtsi","Progorelets","Voynitsi","Yakimovo","Якимово"),2665,new double[]{43.63472,23.3535}),
    SADOVO(List.of("Cheshnegir","Cheshnigurovo","Cheshnigŭrovo","Sadova","Sadovo","Sadowo","Садово"),2656,new double[]{42.13178,24.93999}),
    TOPOLOVO(List.of("Takhtalii","Topolovo","Topolowo","Тополово"),2600,new double[]{41.9,25.0}),
    RAVDA(List.of("Ravda","Ravdas","Rawda","Rhavtha","Равда"),2556,new double[]{42.64185,27.67713}),
    BATANOVTSI(List.of("Batanovci","Batanovitsi","Batanovtsi","Batanovtzi","Batanowzi","Temelkovo","Батановци"),2519,new double[]{42.59692,22.95634}),
    KILIFAREVO(List.of("Kilifarevo","Kilifarewo","Килифарево"),2497,new double[]{42.98333,25.63333}),
    ZLATARITSA(List.of("Slatariza","Zlatarica","Zlataritsa","Zlataritza","Златарица"),2468,new double[]{43.05,25.9}),
    BOROVO(List.of("Borovo","Gorna Manastiritsa","Gorna-Manastiriza","Gorna-Monastir","Gorni-Manastirica","Борово"),2467,new double[]{43.50086,25.80992}),
    SATOVCHA(List.of("Satovca","Satovcha","Satovdza","Satovdža","Satovča","Satowtscha","Сатовча"),2382,new double[]{41.61667,23.98333}),
    SUHINDOL(List.of("Souhyndol","Suchindol","Suhindol","Sukhindol","Сухиндол"),2364,new double[]{43.19167,25.18111}),
    RUEN(List.of("Ruen","Ulanli","Ulanlii","Ulanliy","Руен"),2339,new double[]{42.8,27.28333}),
    BYALA(List.of("Ak Dere","Bela","Biela","Bjala","Bjela","Byala","Byela","Běla","Бяла"),2327,new double[]{42.87426,27.88865}),
    SAMUIL(List.of("Ashiklar","Samuil","Самуил"),2283,new double[]{43.51667,26.75}),
    PORDIM(List.of("Pordim","Pordime","Porodim","Пордим"),2230,new double[]{43.38333,24.85}),
    TSENOVO(List.of("Causevo","Causkioj","Causovo","Cauševo","Cauškiöj","Cenevo","Cenovo","Chaushevo","Chaushovo","Tenovo","Tsenovo","Zenowo","Čaušovo","Čenevo","Ценово"),2229,new double[]{43.53588,25.65764}),
    HAYREDIN(List.of("Chairedin","Eredin","Hajredin","Hayredin","Khairedin","Khajredin","Khayredin","Хайредин"),2228,new double[]{43.60193,23.66135}),
    KERMEN(List.of("Keremenli","Kermen","Kermenli","Kermenlii","Kermenliy","Kermenlu","Kermenlü","Kermon","Кермен"),2222,new double[]{42.5,26.25}),
    GLAVINITSA(List.of("Asfatchioi","Astvatchioi","Asvatchioi","Asvatk'oy","Asvatk’oy","Glavinica","Glavinitsa","Glawinica","Главиница"),2220,new double[]{43.91667,26.83333}),
    CHERNOMORETS(List.of("Agios Nikolo","Chernomorec","Chernomorets","Nikola","Sveti Nicola","Sveti Nikola","Sweti Nikola","Черноморец"),2194,new double[]{42.44408,27.63902}),
    BOYCHINOVTSI(List.of("Boichinovtsi","Bojchinovci","Bojtschinowzi","Boychinovtsi","Бойчиновци"),2181,new double[]{43.47222,23.33583}),
    AHELOY(List.of("Akheloj","Ахелой"),2112,new double[]{42.64987,27.64838}),
    ZEMEN(List.of("Belovo","Bjelovo","Byelovo","Semen","Zemen","Земен"),2107,new double[]{42.47889,22.74917}),
    CHIPROVTSI(List.of("Chiporovtsi","Chiporovtsu","Chiporovtsŭ","Chiprovci","Chiprovtsi","Ciprovci","Ciprovti","Ciprovți","Cziprowci","Tchiprovtsi","Tjiprovtsi","Tschiporowzi","Tschiprowzi","chipurofutsu~i","chyprwftsy","qi pu luo fu qi","Čiprovci","Ћипровци","Чипровци","Чипровці","چیپروفتسی","چیپرۆڤتسی","チプロフツィ","奇普羅夫齊"),2080,new double[]{43.38417,22.88083}),
    OBZOR(List.of("G'ozeken","Giozeken","Gjozeken","Gusiken","Guzuken","Gyuzekioy","Gyuzuken","Güsiken","Güzuken","G’ozeken","Kozjak-Grad","Kozyak-Grad","Obsor","Obzor","ao bu zuo er","bwzwr","Обзор","אובזור","ئۆبزۆر","بوزور","奧布佐爾"),2002,new double[]{42.81998,27.88007}),
    BREZOVO(List.of("Abrashlare","Abraslare","Bresowo","Brezovo","Brezowo","Brjesovo","Bryezovo","Obshtina Brezovo","Obsjtina Brezovo","brzwfw","bu lei zuo wo","burezovu~o","Брезово","برزوفو","برێزۆڤۆ","ブレゾヴォ","布雷佐沃"),1947,new double[]{42.35,25.08333}),
    ALFATAR(List.of("Alfatar","General Lazarovo","General Lazarow","Алфатар"),1916,new double[]{43.94525,27.28751}),
    MIRKOVO(List.of("Mirkovo","Mirkowo","Мирково"),1882,new double[]{42.7,23.98333}),
    GRAMADA(List.of("Gramada","Грамада"),1872,new double[]{43.83738,22.65279}),
    GARMEN(List.of("Garmen","Gurmen","Gărmen","Gŭrmen","Гърмен"),1838,new double[]{41.6,23.81667}),
    BOBOSHEVO(List.of("Bobochevo","Boboschewo","Bobosevo","Boboshevo","Boboševo","Бобочево","Бобошево"),1784,new double[]{42.15296,23.00146}),
    CHELOPECH(List.of("Celopec","Chelopech","Tschelopetsch","Čelopeč","Челопеч"),1760,new double[]{42.7,24.08333}),
    BRUSARTSI(List.of("Brusarci","Brusartsi","Brussarz","Брусарци"),1734,new double[]{43.66075,23.06732}),
    KRUSHARI(List.of("Armuchi","Armutli","Armutlia","Armutlii","Armutlu","Krusari","Krushari","Krušari","Крушари"),1722,new double[]{43.81675,27.75552}),
    ANTON(List.of("Anton","Lashene","Lezhene","Ludzhene","Luzhene","Lăshene","Lŭdzhene","Lŭzhene","Антон"),1697,new double[]{42.75,24.28333}),
    KOLAROVO(List.of("Kolarevo","Kolarewo","Kolarovo","Коларово"),1697,new double[]{41.36385,23.10669}),
    SHIPKA(List.of("Schipka","Shipka","Sipka","Šipka","Шипка"),1604,new double[]{42.71667,25.33333}),
    NOVO_SELO(List.of("Novo Selo","Nowo-Selo","Ново Село"),1574,new double[]{44.16214,22.78376}),
    ANTONOVO(List.of("Antonovo","Poljana","Poljane","Polyana","Polyane","Yayla-K'oy","Yayla-K’oy","Yaylakioi","Антоново"),1543,new double[]{43.15,26.16667}),
    KAOLINOVO(List.of("Beyuk Bakchilar","Boshidar","Bozhidar","Kaolinovo","Shumnu-Bokhchalar","Shumnu-Bokhchilar","Каолиново"),1537,new double[]{43.61667,27.11667}),
    GORNA_MALINA(List.of("Gorna Malina","Горна Малина"),1501,new double[]{42.68333,23.7}),
    KLISURA(List.of("Derbend","Klissoura","Klissura","Klisura","Клисура"),1485,new double[]{42.7,24.45}),
    DIMOVO(List.of("Aleksandrovo","Burzitsa","Bŭrzitsa","Dimovo","Knjas Alexandrowo","Knyaz Aleksandrovo","Osmanie","Vlaykovo","Димово"),1461,new double[]{43.74167,22.72694}),
    SENOVO(List.of("Senevo","Senovo","Senowo","Syenovo","Сеново"),1459,new double[]{43.65,26.36667}),
    VENETS(List.of("K'okledzha","K'oklyudzha","K'okyudzha","Kiokhudza","Kiokhudža","Kokedzha","K’okledzha","K’oklyudzha","K’okyudzha","Venec","Venets","Vyenets","Wenez","Венец"),1450,new double[]{43.55,26.93333}),
    CHAVDAR(List.of("Chavdar","Kolanlare","Kolanlari","Radoslavo","Radoslavovo","Radoslawowo","Чавдар"),1398,new double[]{42.65,24.05}),
    BALGAREVO(List.of("Bolgarevo","Болгарево"),1375,new double[]{43.40296,28.41189}),
    VETRINO(List.of("Asya-Tepe","Jasi Tepe","Vetrino","Vyetreno","Vyetrino","Wetrino","Yasa-Tepe","Yase-Tepe","Yasu-Tepe","Yasă-Tepe","Yasŭ-Tepe","Ветрино"),1368,new double[]{43.31667,27.43333}),
    BOLYAROVO(List.of("Boljarovo","Boljarowo","Bolyarovo","Pachakioi","Pasakioj","Pasha-K'oy","Pasha-Kyoy","Pasha-K’oy","Pashakioy","Pašakiöj","Болярово"),1368,new double[]{42.14962,26.81116}),
    MINERALNI_BANI(List.of("Khaskovski Bani","Khaskovski Mineralni Bani","Mineralni Bani","Mineralni Bani-Haskovo","Минерални Бани"),1367,new double[]{41.91667,25.35}),
    MADZHAROVO(List.of("Dupnitsa","Dupniza","Madjarovo","Madzarovo","Madzarowo","Madzharovo","Madzjarovo","Madżarowo","Madžarovo","Yatadzhik","ma gu luo wo","majarwfw","Маджарово","Маџарово","ماجاروفو","ماجارۆڤۆ","馬賈羅沃"),1319,new double[]{41.63461,25.86439}),
    GARA_HITRINO(List.of("Bahnhof Chitrino","Gara Hitrino","Gara Khitino","Gara Khitrino","Gara Seitandzik","Gara Sejtandzik","Gara Sheytandzhik","Gara Šeitandžik","Gara Šejtandžik","Karola","Seitandzik","Seitantzik","Sejtandzik","Shaytandzhik","Stantsiya Sheytandzhik","Šeitandžik","Šeitantžik","Гара Хитрино"),1302,new double[]{43.43333,26.91667}),
    BANITE(List.of("Banite","Ladsha","Ledzha","Ludzha","Lădsha","Lŭdzha","Баните"),1279,new double[]{41.61667,25.01667}),
    RUZHINTSI(List.of("Beloptichene","Rujintsi","Rushinzi","Ruzhentsi","Ruzhinci","Ruzhintsi","Ruzinci","Ružinci","Ружинци"),1269,new double[]{43.62179,22.83286}),
    PLISKA(List.of("Aboba","Ak Baba","Pliska","Pliskov","Pliskow","Плиска"),1263,new double[]{43.36667,27.11667}),
    BATA(List.of("Bakadzhika","Bakazhek","Bata","Batachik","Batadzhik","Batadzik","Batadžik","Бата"),1235,new double[]{42.73802,27.49643}),
    LESICHOVO(List.of("Lesicevo","Lesichevo","Lesichovo","Lesicovo","Lesičevo","Lesičovo","Lessitschowo","Lisichevo","Ljesicevo","Ljesičevo","Lyesichevo","Лесичово"),1206,new double[]{42.35626,24.1119}),
    SITOVO(List.of("Doimuslar","Doimuşlar","Donnuslar","Donnuşlar","Doymushlar","Sitovo","Sitowo","Ситово"),1140,new double[]{44.0273,27.01982}),
    KITEN(List.of("Kiten","Mukhalii","Китен"),1115,new double[]{43.08333,27.31667}),
    AHTOPOL(List.of("Achtepol","Achtopol","Agathopolis","Ahtapolu","Ahtopol","Akhtebol","Akhtopol","Ахтопол"),1107,new double[]{42.09768,27.93961}),
    KAYNARDZHA(List.of("Cainargcaua-Mica","Cainargeaua Mica","Cainargeaua Mică","Kajnardzha","Kaynardzha","Kutschuk Kainardshi","Kutschük Kainardshi","Kyuchuk-Kaynardzha","Malka Kainardsha","Malka-Kaynardzha","Malka-Kaynaruzha","Malka-Kaynarŭzha","Кайнарджа"),1107,new double[]{43.99278,27.50713}),
    STRUMYANI(List.of("Strumjani","Strumyani","Струмяни"),1058,new double[]{41.63333,23.2}),
    GYOVREN(List.of("G'ovren","Gjowren","Goevren","Gyovren","Gövren","Гьоврен"),1040,new double[]{41.66326,24.37557}),
    RUPITE(List.of("Muetarovo","Muletarovo","Rupite","Schirbanowo","Sirbanovo","Рупите"),1037,new double[]{41.44245,23.24168}),
    IVANOVO(List.of("Ivanovo","Iwanowo","Иваново"),1031,new double[]{43.68568,25.95565}),
    BOYNITSA(List.of("Boinica","Boinitsa","Bojnica","Bojniza","Boynitsa","Бойница"),884,new double[]{43.9565,22.53255}),
    CHUPRENE(List.of("Chuprene","Chupreni","Cupren","Cuprene","Cuprenja","Tschuprene","Čupren","Čuprene","Čuprenja","Чупрене"),842,new double[]{43.51806,22.66611}),
    NEVESTINO(List.of("Kadiin Most","Kadin Most","Kruchma Kadiin-Most","Krŭchma Kadiin-Most","Nevestino","Nevyestaio","Nevyestino","Newestino","Невестино"),779,new double[]{42.25551,22.85175}),
    KIRKOVO(List.of("Kirkova","Kirkovo","Kirkowo","Кирково"),700,new double[]{41.32715,25.36379}),
    MAKRESH(List.of("Makres","Makresch","Makresh","Makreš","Макреш"),660,new double[]{43.76794,22.66406}),
    SPASOVO(List.of("Spasova","Spasovo","Suleimanlak","Syuleymanluk","Syuleymanlŭk","Süleimanlăk","Спасово"),0,new double[]{43.70168,28.30399}),
    LAKATNIK(List.of("Lakatnik","Лакатник"),0,new double[]{43.05,23.4}),
    ASEN(List.of("Asen","Yurenlii","Yurenliy","Асен"),0,new double[]{42.65,25.2}),
    SARNITSA(List.of("S'rnitsa","Sarnitsa","Sarniza","Shabanli","Surnica","Surnitsa","Sŭrnitsa","S’rnitsa","Сърница"),0,new double[]{41.73835,24.02435}),
    MEDOVENE(List.of("Balbunar Endzhe","Enidzhe Balbunar","Indzhekioy","Mediowene","Medovene","Медовене"),0,new double[]{43.76667,26.51667}),
    ZELENIKOVO(List.of("Amzalare","Amzulare","Amzŭlare","Hamzalare","Khamzalare","Selenikowo","Zelenikovo","Зелениково"),0,new double[]{42.4,25.08333}),
    ELKHOVO(List.of("Chatal Tepe","Chital","Elchowo","Elkhovo","Елхово"),0,new double[]{42.38333,25.43333}),
    DRENOVETS(List.of("Chorl'ovo","Chorlevo","Chorl’ovo","Drenovec","Drenovets","Drenowez","Drjenovec","Dryanovets","Dryenovets","Tscherljowo","Дреновец"),0,new double[]{43.69134,22.97365}),
    GORICHEVO(List.of("Gorichevo","Goritschewo","Orman Beshevli","Горичево"),0,new double[]{43.85,26.45}),
    BOV(List.of("Bov","Bow","Бов"),0,new double[]{43.0325,23.37806}),
    TOCHILARI(List.of("Musakhchilar","Musatchilar","Tochilari","Totschilari","Точилари"),0,new double[]{43.85,26.46667});


    private List<String> names;
    private int population;
    private double[] coordinates;
    private String bgName;


    City(List<String> names, int population, double[] coordinates) {
        this.names = names;
        this.population = population;
        this.coordinates = coordinates;
    }

    City(String bgName ,List<String> names, int population, double[] coordinates) {
        this.bgName=bgName;
        this.names = names;
        this.population = population;
        this.coordinates = coordinates;
    }

    public List<String> getNames() {
        return names;
    }

    public void setNames(List<String> names) {
        this.names = names;
    }

    public int getPopulation() {
        return population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    public double[] getCoordinates() {
        return coordinates;
    }

    public void setCoordinates(double[] coordinates) {
        this.coordinates = coordinates;
    }

    public String getBgName() {
        return bgName;
    }

    public void setBgName(String bgName) {
        this.bgName = bgName;
    }



}
